<?php

declare(strict_types=1);

namespace Payment_API\Entity;

use DateTimeImmutable;
use Payment_API\Interface\EntityInterface;
use Payment_API\Enums\CustomerStatus;
use Payment_API\Enums\CustomerType;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'customers')]
class CustomersEntity implements EntityInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id; // Customer ID (Autogenerated)

    #[ORM\Column(type: 'string', length: 20)]
    private string $ucid; // Unique Customer Identifier

    #[ORM\Column(type: 'string', nullable: false, length: 150)]
    private string $name; // Customer Name

    #[ORM\Column(type: 'string', unique: true, length: 255)]
    private string $email; // Customer Email

    #[ORM\Column(type: 'integer', nullable: false, length: 20)]
    private int $phone; // Customer Phone

    #[ORM\Column(type: 'string', nullable: false, length: 255)]
    private string $password; // Customer Password

    #[ORM\Column(type: 'string', nullable: true, updatable: true, length: 255)]
    private string $address; // Customer Address

    #[ORM\Column(type: 'datetime', nullable: false, updatable: true)]
    private DateTimeImmutable $created_at; // Date and Time of Account Creation

    #[ORM\Column(type: 'string', nullable: false, columnDefinition: 'ENUM("active", "inactive")')]
    private CustomerStatus $status; // Customer Account Status

    #[ORM\Column(type: 'string', nullable: false, columnDefinition: 'ENUM("individual", "organization")')]
    private CustomerType $type; // Customer Type

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable('now');
        $this->status = CustomerStatus::ACTIVE;
    }

    public function getID(): int
    {
        return $this->id;
    }

    public function getUCID(): string
    {
        return $this->ucid;
    }

    public function setUCID(string $ucid): void
    {
        $this->ucid = $ucid;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getPhone(): int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): void
    {
        $this->phone = $phone;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = hash(PASSWORD_BCRYPT, $password);
    }

    public function getAddress(): string
    {
        return $this->address;
    }

    public function setAddress(string $address): void
    {
        $this->address = $address;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->created_at;
    }

    public function getStatus(): CustomerStatus
    {
        return $this->status;
    }

    public function setStatus(CustomerStatus $status): void
    {
        $this->status = $status;
    }

    public function getType(): CustomerType
    {
        return $this->type;
    }

    public function setType(CustomerType $type): void
    {
        $this->type = $type;
    }
}
