<?php

declare(strict_types=1);

namespace Payment_API\Entity;

use DateTime;
use Payment_API\Interface\EntityInterface;
use Payment_API\Enums\MethodStatus;
use Doctrine\ORM\Mapping as ORM;
use JsonSerializable;

#[ORM\Entity]
#[ORM\Table(name: 'methods')]
class MethodsEntity implements EntityInterface, JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id; // Method ID (Autogenerated)

    #[ORM\Column(type: 'string', nullable: false, length: 20)]
    private string $umid; // Unique Method Identifier

    #[ORM\Column(type: 'string', nullable: false, updatable: true, length: 150)]
    private string $method_name; // Method Name: GooglePay, ApplePay, AmazonPay

    #[ORM\Column(type: 'datetime', nullable: false, updatable: true)]
    private DateTime $created_at; // Date and Time of Method Creation

    #[ORM\Column(type: 'string', nullable: false, columnDefinition: 'ENUM("active", "inactive")')]
    private string $method_status; // Method Status

    #[ORM\Column(type: 'string', nullable: false, columnDefinition: 'ENUM("card", "bank")')]
    private string $method_type; // Method Type

    public function __construct()
    {
        $this->created_at = new DateTime('now');
        $this->method_status = MethodStatus::ACTIVE->value;
    }

    public function getID(): int
    {
        return $this->id;
    }

    public function getUMID(): string
    {
        return $this->umid;
    }

    public function setUMID(string $umid): void
    {
        $this->umid = $umid;
    }

    public function getMethodName(): string
    {
        return $this->method_name;
    }

    public function setMethodName(string $method_name): void
    {
        $this->method_name = $method_name;
    }

    public function getCreatedAt(): DateTime
    {
        return $this->created_at;
    }

    public function getMethodStatus(): string
    {
        return $this->method_status;
    }

    public function setMethodStatus(string $method_status): void
    {
        $this->method_status = $method_status;
    }

    public function getMethodType(): string
    {
        return $this->method_type;
    }

    public function setMethodType(string $method_type): void
    {
        $this->method_type = $method_type;
    }

    public function jsonSerialize()
    {
        return [
            'unique id' => $this->id,
            'method name' => $this->method_name,
            'method status' => $this->method_status,
            'method type' => $this->method_type
        ];
    }
}
