<?php

declare(strict_types=1);

namespace Payment_API\Entity;

use DateTimeImmutable;
use Payment_API\Interface\EntityInterface;
use Payment_API\Enums\MethodStatus;
use Payment_API\Enums\MethodType;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
#[ORM\Table(name: 'methods')]
class MethodsEntity implements EntityInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private int $id; // Method ID (Autogenerated)

    #[ORM\Column(type: 'string', nullable: false, length: 150)]
    private string $name; // Method Name: GooglePay, ApplePay, AmazonPay

    #[ORM\Column(type: 'string', nullable: false, length: 20)]
    private string $umid; // Unique Method Identifier

    #[ORM\Column(type: 'datetime', nullable: false, updatable: true)]
    private DateTimeImmutable $created_at; // Date and Time of Method Creation

    #[ORM\Column(type: 'string', nullable: false, columnDefinition: 'ENUM("active", "inactive")')]
    private MethodStatus $status; // Method Status

    #[ORM\Column(type: 'string', nullable: false, columnDefinition: 'ENUM("card", "bank")')]
    private MethodType $type; // Method Type

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable('now');
        $this->status = MethodStatus::ACTIVE;
        $this->type = MethodType::CARD;
    }

    public function getID(): int
    {
        return $this->id;
    }

    public function getUMID(): string
    {
        return $this->umid;
    }

    public function setUMID(string $umid): void
    {
        $this->umid = $umid;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->created_at;
    }

    public function getStatus(): MethodStatus
    {
        return $this->status;
    }

    public function setStatus(MethodStatus $status): void
    {
        $this->status = $status;
    }

    public function getType(): MethodType
    {
        return $this->type;
    }

    public function setType(MethodType $type): void
    {
        $this->type = $type;
    }
}
